готово
OlgaJav22/BookRecipesNew pull request #1
Opened 2023-01-16 08:44 UTC by OlgaJav22

2023-01-16 14:49 UTC, OlgaLugacheva requested changes

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +public class IngredientsServiceImpl {
а почему тут ты не используешь интерфейс тогда, а в другом сервисе используешь, давай сделаем чтобы было единообразно.

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/contpollers/RecipesController.java
> +    private final RecipesServiceImpl recipesService;
ижектить нужно интерфейс

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/contpollers/RecipesController.java
> +
лишняя строка

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/contpollers/RecipesController.java
> +    @PutMapping("/app")
PostMapping

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/model/BookRecipes.java
> +    private Ingredients ingredients[];
Может, лучше список использовать?

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/RecipesService.java
> +    BookRecipes appNewRecipes(BookRecipes bookRecipes);
почему app ? 
наверное add ?

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/contpollers/IngredientsController.java
> +    @PutMapping("/app")
PostMapping

2023-01-16 14:49 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/contpollers/IngredientsController.java
> +
лишняя строка

2023-01-16 18:01 UTC, OlgaJav22 commented on src/main/java/me/recipes/bookrecipes/contpollers/RecipesController.java
> +    @PutMapping("/app")
Исправила: не получилось использовать  throw new ServerException()  выдавало следующее (cannot resolve constructor  
unused import statements)  почему, подскажите пожалуйста?

2023-01-16 18:01 UTC, OlgaJav22 commented on src/main/java/me/recipes/bookrecipes/model/BookRecipes.java
> +    private Ingredients ingredients[];
да, согласна

2023-01-16 18:02 UTC, OlgaJav22 commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +public class IngredientsServiceImpl {
можно же один интерфейс использовать? Лично в этой ситуации не понимаю вообще зачем он нужен.

2023-01-17 06:01 UTC, OlgaLugacheva requested changes

2023-01-17 06:01 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +public class IngredientsServiceImpl implements RecipesService {
нет , свой должен быть интерфейс, IngredientService

2023-01-17 06:01 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/RecipesServiceImpl.java
> +    }
эти методы отсюда нужно убрать

2023-01-17 06:01 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +    }
эти методы отсюда нужно убрать

2023-01-17 15:18 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +public class IngredientsServiceImpl {
в принципе в данном случае так как реализация одна можно обойтись вообще без интерфейсов, но должно быть в любом случае единообразие

2023-01-17 16:08 UTC, OlgaLugacheva requested changes

2023-01-17 16:08 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +        ingredientsMap.getOrDefault(countId++, ingredients);
put вместо getOrDefaul

2023-01-17 16:08 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/RecipesServiceImpl.java
> +        bookRecipesMap.getOrDefault(lastId++, bookRecipes);
put

2023-01-17 16:55 UTC, OlgaJav22 commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +        ingredientsMap.getOrDefault(countId++, ingredients);
нам Зураб так рекомендовал в уроке, на случай если карта пустая. А почему нельзя так оставить?

2023-01-17 17:54 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/IngredientsServiceImpl.java
> +        ingredientsMap.getOrDefault(countId++, ingredients);
Зураб все верно рекомендовал но только для получения ингредиента а не добавления

2023-01-17 17:55 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/services/impl/RecipesServiceImpl.java
> +        bookRecipesMap.getOrDefault(lastId++, bookRecipes);
все-таки put

2023-01-17 17:58 UTC, OlgaLugacheva requested changes

2023-01-17 17:58 UTC, OlgaLugacheva commented on src/main/java/me/recipes/bookrecipes/contpollers/IngredientsController.java
> +    @GetMapping("/countId")
@GetMapping("/{countId}")

2023-01-19 11:18 UTC, OlgaLugacheva approved these changes

2023-01-19 16:50 UTC, merged